name: rutils_logger
description: RUtils logger
version: 0.0.2+1

environment:
  sdk: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  logging_appenders: ^1.0.0

dev_dependencies:
  lints: ^1.0.0
