name: rutils_logger
description: RUtils logger
version: 0.0.3

environment:
  sdk: ">=3.3.0"
  flutter: 3.24.2

dependencies:
  flutter:
    sdk: flutter
  logging_appenders: ^1.3.1

dev_dependencies:
  lints: ^5.0.0
