name: rutils_image
description: RUtils image package
version: 0.0.3

environment:
  sdk: ">=3.3.0"
  flutter: 3.24.2

dependencies:
  flutter:
    sdk: flutter
  permission_handler: ^12.0.0
  image_picker: ^1.1.2
  image_cropper: ^9.1.0
  path_provider: ^2.1.5

dev_dependencies:
  lints: ^5.0.0
