name: rutils_location
description: RUtils location package
version: 0.0.2+1

environment:
  sdk: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  geolocator: ^7.2.0+1

dev_dependencies:
  lints: ^1.0.0

flutter:
