name: rutils_location
description: RUtils location package
version: 0.0.2

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  geolocator: ^7.2.0+1

dev_dependencies:
  lints: ^1.0.0

flutter:
