name: rutils_uikit
description: RUtils uikit package
version: 0.0.2+1

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: 3.24.2

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.1.0
  intl: ^0.20.2

dev_dependencies:
  lints: ^5.0.0

flutter:
  assets:
    - assets/icons/
