name: rutils_location
description: RUtils location package
version: 0.0.3

environment:
  sdk: ">=3.3.0"
  flutter: 3.24.2

dependencies:
  flutter:
    sdk: flutter
  geolocator: ^14.0.0

dev_dependencies:
  lints: ^5.0.0
