name: rutils_example
description: A rutils_example project

publish_to: "none"

version: 1.1.0

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  rutils_uikit:
    path: ../rutils_uikit

flutter:
  uses-material-design: true
