name: "PR Title is Conventional"
on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize

jobs:
  main:
    name: Check title
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v3.4.1
        with:
          validateSingleCommit: true
        env:
          GITHUB_TOKEN: ${{ secrets.END_USER_GITHUB_TOKEN }}
